name: "ASIMOV build rust action"
author: "ASIMOV by Haltia.AI <support@asimov.so>"
description: "Action to help automate building rust crates"
inputs:
  target:
    description: "Target to build for."
    required: true
  profile:
    description: "Profile to build with. Defaults to release."
    required: false
    default: "release"
  glibc-version:
    description: "Version of GLIBC to link to. Only works on Linux and using zigbuild. Defaults to system default."
    required: false
  artifact-prefix:
    description: "Prefix for the output artifact name. Defaults to empty string."
    required: false
  artifact-suffix:
    description: "Suffix for the output artifact name. Defaults to target."
    required: false
  artifact-name:
    description: "Name of the output artifact. Must be unique. Prepended with artifact-prefix and appended with artifact-suffix. Defaults to binary being built."
    required: false
  packages-to-build:
    description: "Name of the packages to build, separated by space. Defaults to workspace's default-members that have at least one binary target."
    required: false
  targets-to-build:
    description: "Name of the targets to build. Defaults to all binary targets in the packages-to-build."
    required: false
  binary-extension:
    description: "Extension for the output binary file. Defaults to 'exe' for Windows targets and empty on other platforms."
    required: false
  working-directory:
    description: "Working directory. Defaults to root."
    required: false
    default: "."
  checkout:
    description: "Checkout repository? Defaults to true."
    required: false
    default: "true"
  rust-toolchain:
    description: "Rust toolchain to use. Defaults to stable."
    required: false
    default: "stable"
  install-macos-sdk:
    description: "Install MacOS SDK? Only works with zigbuild. Defaults to false."
    required: false
    default: "false"
  use-zigbuild:
    description: "Use cargo-zigbuild? Defaults to false."
    required: false
    default: "false"
  extra-build-arguments:
    description: "Extra arguments to pass to cargo build. Defaults to empty string."
    required: false
    default: ""
  strip-artifact:
    description: "Strip symbols? Defaults to false."
    required: false
    default: "false"
  compress-artifact:
    description: "Compress artifact? Defaults to true."
    required: false
    default: "true"
  upload-artifact:
    description: "Upload artifact? Defaults to true."
    required: false
    default: "true"
outputs:
  target-dir:
    description: "Path to the build directory (target directory)."
    value: ${{ steps.globals.outputs.build_dir }}
  # artifact-path:
  #   description: "Path to an Artifact."
  #   value: ${{ steps.finalize.outputs.artifact-path }}
  # artifact-id:
  #   description: "GitHub ID of an Artifact, can be used by the REST API."
  #   value: ${{ steps.upload.outputs.artifact-id }}
  # artifact-url:
  #   description: "URL to download an Artifact."
  #   value: ${{ steps.upload.outputs.artifact-url }}
runs:
  using: "composite"
  steps:
    - name: Install Rust and target
      id: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        target: ${{ inputs.target }}
    - name: Checkout repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.working-directory }}
    - name: Prepare environment
      id: globals
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        METADATA=$(cargo metadata --format-version 1 --no-deps)

        if [[ -z "${{ inputs.packages-to-build }}" ]]; then
          PACKAGES_TO_BUILD=$(echo "$METADATA" | jq -r '. as $root | [.packages[] | select(.id | IN($root.workspace_default_members[])) | select(any(.targets[]; .kind[] | contains("bin"))) | .name] | join(" ")')
          if [[ -z "$PACKAGES_TO_BUILD" ]]; then
            echo "::error::No valid packages found. Please specify packages-to-build input."
            exit 1
          fi
        else
          PACKAGES_TO_BUILD="${{ inputs.packages-to-build }}"
        fi

        TARGET_WITH_GLIBC="${{ inputs.target }}${{ inputs.glibc-version != '' && '.' || '' }}${{ inputs.glibc-version }}"
        IS_TARGET_WINDOWS="${{ contains(inputs.target, 'windows') }}"
        OUTPUT_DIR="output"
        TARGET_DIR=$(echo "$METADATA" | jq -r '.target_directory')
        BUILD_DIR="${TARGET_DIR}/${{ inputs.target }}/${{ inputs.profile }}"
        TARGETS_TO_BUILD=$(echo "$METADATA" | jq --arg packages_to_build "$PACKAGES_TO_BUILD" -r '. as $root | [.packages[] | select(.name as $n | ($packages_to_build | split(" ") | index($n))) | .targets[] | select(.kind[] | contains("bin")) | .name] | join(" ")')
        PACKAGES_MAP=$(echo "$METADATA" | jq -r '[.packages[] | select([.targets[] | select(.kind[] | contains("bin"))] | length > 0) | "\(.name)=\([.targets[] | select(.kind[] | contains("bin")) | .name] | join(","))"] | join(" ")')

        echo "target_with_glibc=$TARGET_WITH_GLIBC" >> $GITHUB_OUTPUT
        echo "is_target_windows=$IS_TARGET_WINDOWS" >> $GITHUB_OUTPUT
        echo "output_dir=$OUTPUT_DIR" >> $GITHUB_OUTPUT
        echo "target_dir=$TARGET_DIR" >> $GITHUB_OUTPUT
        echo "build_dir=$BUILD_DIR" >> $GITHUB_OUTPUT
        echo "packages_to_build=$PACKAGES_TO_BUILD" >> $GITHUB_OUTPUT
        echo "targets_to_build=$TARGETS_TO_BUILD" >> $GITHUB_OUTPUT
        echo "packages_map=$PACKAGES_MAP" >> $GITHUB_OUTPUT
    - name: Install MinGW
      if: ${{ runner.os != 'windows' && inputs.target == 'x86_64-pc-windows-gnu' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -yq --no-install-recommends mingw-w64
    - name: Install macOS SDK
      id: macos-sdk
      if: ${{ inputs.install-macos-sdk == 'true' }}
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        curl -L https://github.com/roblabla/MacOSX-SDKs/releases/download/13.3/MacOSX13.3.sdk.tar.xz | tar xJ
        echo "root=$(pwd)/MacOSX13.3.sdk/" >> $GITHUB_OUTPUT
    - name: Install zig
      if: ${{ inputs.use-zigbuild == 'true' }}
      uses: mlugg/setup-zig@v2
    - name: Install cargo-zigbuild
      if: ${{ inputs.use-zigbuild == 'true' }}
      shell: bash
      run: cargo install --locked cargo-zigbuild
    - name: Set Perl environment variables
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        echo "OPENSSL_SRC_PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
    - name: Build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        BUILD_ARG="${{ inputs.use-zigbuild == 'true' && 'zigbuild' || 'build' }}"
        PACKAGES_TO_BUILD=(${{ steps.globals.outputs.packages_to_build }})
        PACKAGE_ARG="${PACKAGES_TO_BUILD[@]/#/--package }"
        TARGETS_TO_BUILD=(${{ steps.globals.outputs.targets_to_build }})
        TARGET_ARG="${TARGETS_TO_BUILD[@]/#/--bin }"
        export SDKROOT="${{ inputs.use-zigbuild == 'true' && steps.macos-sdk.outputs.root || '' }}"
        cargo +${{ steps.toolchain.outputs.name }} $BUILD_ARG --profile ${{ inputs.profile }} $PACKAGE_ARG $TARGET_ARG --target ${{ steps.globals.outputs.target_with_glibc }} ${{ inputs.extra-build-arguments }}
    - name: Move artifacts
      id: move
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir ${{ steps.globals.outputs.output_dir }}

        TARGETS_TO_BUILD=(${{ steps.globals.outputs.targets_to_build }})
        EXT="${{ inputs.binary-extension }}"
        PREFIX="${{ inputs.artifact-prefix }}"
        SUFFIX="${{ inputs.artifact-suffix != '' && inputs.artifact-suffix || inputs.target }}"
        EXT="${EXT:+.}${EXT}"
        PREFIX="$PREFIX${PREFIX:+-}"
        SUFFIX="${SUFFIX:+-}$SUFFIX"
        TARGETS=()

        for TARGET in "${TARGETS_TO_BUILD[@]}"; do
          NAME="${{ inputs.artifact-name != '' && inputs.artifact-name || '$TARGET' }}"
          RESULT="$PREFIX$NAME$SUFFIX$EXT"
          echo "target result: $RESULT"

          BUILD_PATH="${{ steps.globals.outputs.build_dir }}/$TARGET$EXT"
          OUTPUT_PATH="${{ steps.globals.outputs.output_dir }}/$RESULT"

          TARGETS+=("$OUTPUT_PATH")

          cp "$BUILD_PATH" "$OUTPUT_PATH"
        done

        echo "targets=${TARGETS[@]}" >> $GITHUB_OUTPUT
    - name: Strip artifacts
      if: ${{ inputs.strip-artifact == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        TARGETS=(${{ steps.move.outputs.targets }})

        for TARGET in "${TARGETS[@]}"; do
          strip "$TARGET"
        done
    - name: Compress or archive artifacts
      id: compress
      if: ${{ inputs.compress-artifact == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        PACKAGES=(${{ steps.globals.outputs.packages_to_build }})
        PACKAGES_MAP=(${{ steps.globals.outputs.packages_map }})
        OUTPUT=()

        for PACKAGE_ENTRY in "${PACKAGES_MAP[@]}"; do
          PACKAGE_NAME="${PACKAGE_ENTRY%%=*}" # remove everything after the first '='
          PACKAGE_TARGETS="${PACKAGE_ENTRY#*=}" # remove everything before the first '='
          FILES="${PACKAGE_TARGETS//,/ }" # convert from comma-separated to space-separated

          OUTPUT_PATH="${{ steps.globals.outputs.output_dir }}/${PACKAGE_NAME}"
          
          if [ "$RUNNER_OS" = "Windows" ]; then
            OUTPUT_PATH="$OUTPUT_PATH.zip"
            7z a -tzip -sdel "$OUTPUT_PATH" $FILES
          elif [ "${{ steps.globals.outputs.is_target_windows }}" = "true" ]; then
            OUTPUT_PATH="$OUTPUT_PATH.zip"
            zip -mj "$OUTPUT_PATH" $FILES
          else
            OUTPUT_PATH="$OUTPUT_PATH.gz"
            tar -czf "$OUTPUT_PATH" --remove-files $FILES
          fi

          OUTPUT+=("$OUTPUT_PATH")
        done

        echo "output-path=${OUTPUT[@]}" >> $GITHUB_OUTPUT
    - name: Upload artifact
      id: upload
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.target }}
        path: ${{ inputs.working-directory }}/${{ steps.globals.outputs.output_dir }}/*
        if-no-files-found: error
    # - name: Write outputs
    #   id: finalize
    #   shell: bash
    #   run: |
    #     if [ "${{ inputs.compress-artifact }}" == "true" ]; then
    #       echo "artifact-path=${{ steps.compress.outputs.output-path }}" >> $GITHUB_OUTPUT
    #     else
    #       echo "artifact-path=${{ inputs.working-directory }}/${{ steps.globals.outputs.output_artifact_path_ext }}" >> $GITHUB_OUTPUT
    #     fi
